# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9323be29801aae98447ee29d208d8222f1465f6d92aa6c31db068c429000abe2433522c9eb02e182be41e3c104281b869dc018ee847bfb45b83029227f347e66

test:
  secret_key_base: 3218d3dc48b185f6b936634552788e41f565c588327feef2baf33d394f61bd688db47927cedf84e0651c1eaf5266f1e203298abff4bac6b5a65080fdfc06b5ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
